name: Build cage

on:
  workflow_dispatch:
  push:
    paths:
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep wlroots -y
        sudo sed -i 's/focal/jammy/g' /etc/apt/sources.list
        sudo apt update
        sudo apt install meson libwayland-server0

    - uses: actions/checkout@v4

    - name: Execute build script
      run: ./build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: cage_xtmapper
        path: ./build/installed
